apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::703460697499:role/my-eks-cluster-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::703460697499:user/terraform_admin
      username: terraform_admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::703460697499:root
      username: root
      groups:
        - system:masters